In [1]:
import numpy as np

In [3]:
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,0])

In [7]:
array1+array2

array([ 7,  9, 11, 13,  5])

In [9]:
import pandas as pd

In [39]:
details = {
    'Name': ['rohan', 'lohan', 'mohan'],
    'Age': [19, 20, 18],
    'University': ['o', 'jj', 'k']
}

In [41]:
df=pd.DataFrame(details)

In [49]:
df.head(1)

Name  Age University
0  rohan   19          o

In [51]:
df.head(2)

Name  Age University
0  rohan   19          o
1  lohan   20         jj

In [53]:
df.head()

Name  Age University
0  rohan   19          o
1  lohan   20         jj
2  mohan   18          k

In [55]:
df.describe

<bound method NDFrame.describe of     Name  Age University
0  rohan   19          o
1  lohan   20         jj
2  mohan   18          k>

In [57]:
df.tail(1)

Name  Age University
2  mohan   18          k

In [67]:
df.shape

(3, 3)

In [73]:
X=df.drop('University',axis=1)
y=df['University']

In [75]:
df.head()

Name  Age University
0  rohan   19          o
1  lohan   20         jj
2  mohan   18          k

In [77]:
matrix=df.to_numpy()

In [79]:
matrix

array([['rohan', 19, 'o'],
       ['lohan', 20, 'jj'],
       ['mohan', 18, 'k']], dtype=object)

In [121]:
#Ye operation se 1D-> 2D main conver ho jayega
arr_1d = np.array([1, 2, 3, 4, 5, 6]) 

arr_2d = arr_1d.reshape(2, 3)  #  Works fine (2x3 = 6 elements)
print("2D Array:\n", arr_2d)



2D Array:
 [[1 2 3]
 [4 5 6]]


In [135]:
#Operation to convert 1D to 3d will be as follows
import pandas as pd
import numpy as np


arr_1d = np.arange(24)

arr_3d=arr_1d.reshape(2,3,4)

arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])