In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('test.csv')

In [9]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [15]:
from sklearn.model_selection import train_test_split


In [91]:
X=df.drop('Id',axis=1)

In [93]:
y=df['Id']

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (1166, 10)
X_test shape: (292, 10)


In [103]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [120]:
st=le.fit(y_train)

In [122]:
st

LabelEncoder()

In [140]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample text data
text_data = ["I love programming", "Python is amazing", "I love Python"]

# Initialize CountVectorizer
cv = CountVectorizer()

# Fit and transform the text data
X = cv.fit_transform(text_data)

# Con
print(X.toarray())



[[0 0 1 1 0]
 [1 1 0 0 1]
 [0 0 1 0 1]]
